# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "doc_files",
    srcs = glob(["**/*.md"]) + [
        "//sw/device/silicon_creator/manuf/data:manuf_testplan.hjson",
        "//sw/device/silicon_creator/manuf/extensions:doc_files",
        "//sw/device/silicon_creator/manuf/keys:doc_files",
    ],
)
